name: satursun_app
description: A Flutter project for Satursun Freelance App

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_storage: ^13.0.4
  cloud_firestore: ^6.1.0
  firebase_messaging: ^16.0.4
  firebase_database: ^12.1.0
  google_sign_in: ^7.2.0
  go_router: ^17.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/get_started.png
    - assets/google.png
    - assets/facebook.png
    - assets/otp_illustration.png
    - assets/freelancer_icon.png
    - assets/client_icon.png

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NunitoSans-Black.ttf
          weight: 900